version: '3.9'
services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      CACHE_DRIVER: database
      QUEUE_CONNECTION: sync
      DB_DATABASE: /var/www/html/database/database.sqlite
    command: >
      /bin/bash -c "
        if [ ! -f .env ]; then
          cp .env.example .env &&
          php artisan key:generate
        fi &&
        touch database/database.sqlite &&
        chown -R www-data:www-data database &&
        chmod -R 775 database &&
        php artisan migrate --force &&
        apache2-foreground
      "
